benchmark: lin
width: [10]
quiet: False
Ndata: 2500
stopping-criterion:
  mode: error   # Train to target error or loss minimum
  target-error: [0.1, 0.1]
  loss-stop: 0.00095 
  loss-grad-stop: .inf
  loss-grad-grad-stop: .inf
optimizer:
  type: AdamW   #AdamW, SGD
  lr: 1e-3
verifier: "dreal" # dreal, z3
output-type: [plot, flowpipe] # None, xml, plot, csv
output-file: test  # Exclude extension 
timeout: False
timeout-duration: 120
seed: 0
repeat: 1
save-net: False
bounded-time: True
time-horizon: 1.0
template: pwa # pwc, pwa, sig
initial: "x0==0.2 & x1==0.2 & t==0" # Note, spaceex and flowstar use different syntax
spaceex: True
flowstar: False
prune: False
error-check: True
n-procs: 1
